# Generated by Django 4.0 on 2023-02-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mecanico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mecanico',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='mecanico/%Y/%m/%d'),
        ),
    ]
