# Generated by Django 4.0 on 2023-01-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='direccion'),
        ),
    ]
