# Generated by Django 4.0 on 2023-01-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_profile_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fechanacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ocupacion'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='telefono'),
        ),
    ]
