# Generated by Django 4.0 on 2023-01-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_profile_fechanacimiento_profile_ocupacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='placa')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=30, null=True, verbose_name='modelo')),
                ('anovehiculo', models.DateField(blank=True, null=True, verbose_name='año del vehiculo')),
            ],
        ),
    ]
