# Generated by Django 4.0 on 2023-01-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
    ]
