# Generated by Django 4.0 on 2023-01-10 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_profile_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.vehiculo'),
        ),
    ]
