# Generated by Django 4.0 on 2023-01-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_profile_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='duenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile'),
        ),
    ]
