# Generated by Django 4.0 on 2023-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_remove_profile_vehiculo_vehiculo_duenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('titulo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Titulo del Servicio')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion del Servicio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precio del Servcio')),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
            },
        ),
    ]
