# Generated by Django 4.0 on 2023-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=30, null=True, verbose_name='placa')),
                ('marca', models.CharField(blank=True, max_length=30, null=True, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=30, null=True, verbose_name='modelo')),
                ('anovehiculo', models.DateField(blank=True, null=True, verbose_name='año del vehiculo')),
                ('duenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.profile')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
            },
        ),
    ]
